### ISSUE TITLE
Material Hive displays more than what we have configured to be accepted in recipes

### ISSUE THREAD

**Issue by Nekosity12** [ProfElements/DynaTech#130]
When you view the material hive it shows you what materials are accepted, we have removed a few resources we felt were too op to duplicate with bees on our server. However the material hive still displays them such as reinforced alloy ingot or hardened metal which our config has neither.
https://i.imgur.com/ZxGEnhk.png

**Comment by Nekosity12** [comment]
Update, it is ignoring our config and allows you to duplicate the resources regardless of what is configured.
`MATERIAL_HIVE:
  enabled: true
  can-be-used-in-workbenches: false
  hide-in-guide: false
  allow-enchanting: true
  allow-disenchanting: true
  slimefun-items-accepted:
  - COPPER_INGOT
  - TIN_INGOT
  - SILVER_INGOT
  - ALUMINUM_INGOT
  - LEAD_INGOT
  - ZINC_INGOT
  - MAGNESIUM_INGOT
  - STEEL_INGOT
  - DURALUMIN_INGOT
  - BILLION_INGOT
  - BRASS_INGOT
  - GILDED_IRON
  - NICKEL_INGOT
  - COBALT_INGOT
  - SYNTHETIC_DIAMOND
  - SYNTHETIC_EMERALD
  - SYNTHETIC_SAPPHIRE
  - CARBON_CHUNK
  vanilla-items-accepted:
  - IRON_INGOT
  - GOLD_INGOT
  - NETHERITE_INGOT
  - DIAMOND
  - EMERALD
  - LAPIS_LAZULI
  - QUARTZ
  - REDSTONE
  - COAL`

**Comment by Nekosity12** [comment]
Issue doesn't seem to be fixed at all:
https://youtu.be/Ti_NTGRmyzI
Timestamps:
0:00 - 0:40
4:50 - 5:00
6:05 - 6:12

**Comment by Skizzles** [comment]
Any update on this? 9 days of items duplicating

**Comment by ProfElements** [comment]
This should be fixed with the latest commit. However the default recipes that are displayed in the book will still be displayed since  I can't access the actual value during registering the recipe (which is why people could still duplicate the defaults when I did the original commit) Yell at me to open this again if it still unfixed.

**Comment by Skizzles** [comment]
@ProfElements Tested on latest jar, this still occurs for items that are not in the designated list.

**Comment by ProfElements** [comment]
@Skizzles with 8c473a6 it should be properly setup now 👍 I forgot `postRegister` so now you should be able to see available recipes and use just them lol

**Comment by Skizzles** [comment]
[01:02:31] [Server thread/ERROR]: [DynaTech] Item "MATERIAL_HIVE" from DynaTech vDEV - 157 (git c0013be6) has caused an Error!
[01:02:31] [Server thread/ERROR]: [DynaTech] You can report it here: https://github.com/ProfElements/DynaTech/issues
[01:02:31] [Server thread/ERROR]: [DynaTech] Registering MaterialHive - 'MATERIAL_HIVE' (DynaTech vDEV - 157 (git c0013be6)) has failed!
java.lang.NullPointerException: Cannot invoke "io.github.thebusybiscuit.slimefun4.api.items.SlimefunItem.getItem()" because the return value of "io.github.thebusybiscuit.slimefun4.api.items.SlimefunItem.getById(String)" is null
	at me.profelements.dynatech.items.electric.MaterialHive.registerDefaultHiveRecipes(MaterialHive.java:89) ~[DynaTech - DEV 157 (git c0013).jar:?]
	at me.profelements.dynatech.items.electric.MaterialHive.postRegister(MaterialHive.java:102) ~[DynaTech - DEV 157 (git c0013).jar:?]
	at io.github.thebusybiscuit.slimefun4.api.items.SlimefunItem.register(SlimefunItem.java:484) ~[Slimefun4 - DEV 997 (git 014f8) (1).jar:?]
	at me.profelements.dynatech.items.electric.abstracts.AMachine.register(AMachine.java:405) ~[DynaTech - DEV 157 (git c0013).jar:?]
	at me.profelements.dynatech.setup.DynaTechItemsSetup.setup(DynaTechItemsSetup.java:430) ~[DynaTech - DEV 157 (git c0013).jar:?]
	at me.profelements.dynatech.DynaTech.onEnable(DynaTech.java:54) ~[DynaTech - DEV 157 (git c0013).jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Purpur-1428]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Purpur-1428]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Purpur-1428]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[patched_1.17.1.jar:git-Purpur-1428]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[patched_1.17.1.jar:git-Purpur-1428]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:736) ~[patched_1.17.1.jar:git-Purpur-1428]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:353) ~[patched_1.17.1.jar:git-Purpur-1428]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1233) ~[patched_1.17.1.jar:git-Purpur-1428]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[patched_1.17.1.jar:git-Purpur-1428]
	at java.lang.Thread.run(Thread.java:831) ~[?:?]
	
	@ProfElements

**Comment by ProfElements** [comment]
One of your MaterialHive configured items slimefun id isn't valid. Could I get a paste of your Items.yml

**Comment by ProfElements** [comment]
That error would be a seperate issue then this one. Please make a new bug report :)

**Comment by ChitterChatter** [comment]
Hi there, I am having a MaterialHive error too...It says 

 'MATERIAL_HIVE' (DynaTech vDEV - 158 (git d9931e35)) has failed!
 
 Is this the same as the ones above?



[Fri, 28. Jan 2022 16:35:51 UTC INFO] Enabling LiteXpansion vDEV - 163 (git 26e59af7)
[Fri, 28. Jan 2022 16:35:51 UTC INFO] Loaded 35 UU-Matter recipes
[Fri, 28. Jan 2022 16:35:51 UTC INFO] Enabling InfinityExpansion vDEV - 130 (git a2773c83)
[Fri, 28. Jan 2022 16:35:51 UTC INFO] Enabling DynaTech vDEV - 158 (git d9931e35)
[Fri, 28. Jan 2022 16:35:51 UTC INFO] Preparing start region for dimension minecraft:dimensionalhome
[8:35 AM]
[Fri, 28. Jan 2022 16:35:51 UTC INFO] Preparing spawn area: 0%
[Fri, 28. Jan 2022 16:35:56 UTC INFO] Time elapsed: 358 ms
[Fri, 28. Jan 2022 16:35:56 UTC INFO] [WorldGuard] (dimensionalhome) TNT ignition is PERMITTED.
[Fri, 28. Jan 2022 16:35:56 UTC INFO] [WorldGuard] (dimensionalhome) Lighters are PERMITTED.
[Fri, 28. Jan 2022 16:35:56 UTC INFO] [WorldGuard] (dimensionalhome) Lava fire is PERMITTED.
[Fri, 28. Jan 2022 16:35:56 UTC INFO] [WorldGuard] (dimensionalhome) Fire spread is UNRESTRICTED.
[Fri, 28. Jan 2022 16:35:56 UTC INFO] [WorldGuard] Loaded configuration for world 'dimensionalhome'
[Fri, 28. Jan 2022 16:35:56 UTC INFO] Loaded 3 maps of world 'dimensionalhome'.
[Fri, 28. Jan 2022 16:35:56 UTC INFO] Loading Blocks for World "dimensionalhome"
[Fri, 28. Jan 2022 16:35:56 UTC INFO] This may take a long time...
[Fri, 28. Jan 2022 16:35:56 UTC INFO] Loading Blocks... 100% (FINISHED - 0ms)
[Fri, 28. Jan 2022 16:35:56 UTC INFO] Loaded a total of 0 Blocks for World "dimensionalhome"
[Fri, 28. Jan 2022 16:35:56 UTC ERROR] Item "MATERIAL_HIVE" from DynaTech vDEV - 158 (git d9931e35) has caused an Error!
[Fri, 28. Jan 2022 16:35:56 UTC ERROR] You can report it here: https://github.com/ProfElements/DynaTech/issues
[Fri, 28. Jan 2022 16:35:56 UTC ERROR] Registering MaterialHive - 'MATERIAL_HIVE' (DynaTech vDEV - 158 (git d9931e35)) has failed!
[Fri, 28. Jan 2022 16:35:56 UTC INFO] Enabling SimpleUtils vDEV - 15 (git 4250fd5e)
[Fri, 28. Jan 2022 16:35:56 UTC INFO] Enabling SlimeTinker vDEV - 59 (git 35f2202a)
[Fri, 28. Jan 2022 16:35:56 UTC INFO]

**Comment by ProfElements** [comment]
Make a new report please
