### ISSUE TITLE
With DynaTech installed, GPS is not available

### ISSUE THREAD

**Issue by laolu77** [ProfElements/DynaTech#153]
## Description (Required)
Like the title, with DynaTech, Slimefun's GPS, it's not available
## Steps to reproduce the Issue (Required)
There are no screenshots and videos, because DynaTech is installed, it is directly unavailable, so there is no need to upload pictures or videos
## Expected behavior (Required)
I hope to fix this bug
## Server Log / Error Report
[Slimefun] 无法通过“BlockUseHandler” GEOScanner - 'GPS_GEO_SCANNER' (Slimefun vdab458c-canary)
java.lang.NoSuchFieldError: MEADOW
at me.profelements.dynatech.items.misc.StarDustMeteor.getDefaultSupply(StarDustMeteor.java:61) ~[DynaTech-Build 31 zh-CN(ybw0014) ) (git 2b70f55) (2).jar:?]
at io.github.thebusybiscuit.slimefun4.api.geo.ResourceManager.generate(ResourceManager.java:176) ~[Slimefun-dab458c-canary.jar:?]
在 io.github.thebusybiscuit.slimefun4.api.geo.ResourceManager.scan(ResourceManager.java:239) ~[Slimefun-dab458c-canary.jar:?]
在 io.github.thebusybiscuit.slimefun4.implementation.items.geo。 GEOScanner.lambda$getItemHandler$0(GEOScanner.java:38) ~[Slimefun-dab458c-canary.jar:?]
at io.github.thebusybiscuit.slimefun4.implementation.listeners.SlimefunItemInteractListener.lambda$rightClickBlock$1(SlimefunItemInteractListener.java:121 ) ~[Slimefun-dab458c-canary.jar:?]
at io.github.thebusybiscuit.slimefun4.api.items.SlimefunItem.callItemHandler(SlimefunItem.java:965) ~[Slimefun-dab458c-canary.jar:?]
at io .github.thebusybiscuit.slimefun4.implementation.listeners.SlimefunItemInteractListener.rightClickBlock(SlimefunItemInteractListener.java:121) ~[Slimefun-dab458c-canary.jar:?]
在 io.github.thebusybiscuit.slimefun4.implementation.listeners.SlimefunItemInteractListener.onRightClick(SlimefunItemInteractListener.java:71) ~[Slimefun-dab458c-canary.jar:?]
在 com.destroystokyo.paper.event.executor.asm.generated。 GeneratedEventExecutor445.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Paper-411]
at co。 aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-411]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1 .jar:git-Paper-411]
在 org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Paper-411]
在 org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:543) ~[patched_1.17.1.jar:git-Paper-411]
在 net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode. java:542) ~[app:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1815) ~[app:?]
at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle( ServerboundUseItemOnPacket.java:33) ~[app:?]
at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[app:?]
at net.minecraft.network.protocol.PacketUtils。 lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[app:?]
在 net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-411]
在 net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[app:?]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[app:?]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1426) ~[ patched_1.17.1.jar:git-Paper-411]
在 net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Paper-411]
在 net.minecraft.util。 thread.BlockableEventLoop.pollTask​​(BlockableEventLoop.java:122) ~[app:?]
at net.minecraft.server.MinecraftServer.pollTask​​Internal(MinecraftServer.java:1404) ~[patched_1.17.1.jar:git-Paper-411]
在 net.minecraft.server.MinecraftServer.pollTask​​(MinecraftServer.java:1397) ~[patched_1.17.1.jar:git-Paper-411]
在 net.minecraft.util.thread.BlockableEventLoop.runAllTask​​s(BlockableEventLoop.java:110) ~[app:?]
在 net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1536) ~[patched_1.17.1.jar:git-Paper-411]
在 net.minecraft.server.MinecraftServer.runServer(MinecraftServer. java:1282) ~[patched_1.17.1.jar:git-Paper-411]
在 net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper- 411]
在 java.lang.Thread.run(Thread.java:833) ~[?:?]
## Environment (Required)
![WL2}J A{6WR~E1WDEV1U$10](https://user-images.githubusercontent.com/80940611/179399275-652ddba5-c684-4e5a-882a-790279489f11.png)

**Comment by ProfElements** [comment]
This due to you running on an older version then 1.19 please update your minecraft server version.
