### ISSUE TITLE
NullPointerException: Profile name must not be null

### ISSUE THREAD

**Issue by IAISI** [ProfElements/DynaTech#201]
## Description (Required)
Latest version of plugin does not load.

## Steps to reproduce the Issue (Required)
Create new server, add latest SF4 and DynaTech

## Server Log / Error Report
```
[21:25:00] [Server thread/ERROR]: Error occurred while enabling DynaTech vDEV - 201 (git 0feb2ee0) (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at me.profelements.dynatech.setup.DynaTechItemsSetup.setup(DynaTechItemsSetup.java:82) ~[SlimefunDynaTech.jar:?]
	at me.profelements.dynatech.DynaTech.onEnable(DynaTech.java:53) ~[SlimefunDynaTech.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190) ~[paper-1.20.2.jar:git-Paper-309]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.2.jar:git-Paper-309]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:646) ~[paper-1.20.2.jar:git-Paper-309]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:557) ~[paper-1.20.2.jar:git-Paper-309]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:627) ~[paper-1.20.2.jar:git-Paper-309]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424) ~[paper-1.20.2.jar:git-Paper-309]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.2.jar:git-Paper-309]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1086) ~[paper-1.20.2.jar:git-Paper-309]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-309]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.NullPointerException: Profile name must not be null
	at java.util.Objects.requireNonNull(Objects.java:235) ~[?:?]
	at com.mojang.authlib.GameProfile.<init>(GameProfile.java:31) ~[authlib-5.0.47.jar:?]
	at org.bukkit.craftbukkit.v1_20_R2.inventory.CraftMetaSkull.setOwningPlayer(CraftMetaSkull.java:248) ~[paper-1.20.2.jar:git-Paper-309]
	at me.profelements.dynatech.dough.skins.CustomGameProfile.apply(CustomGameProfile.java:40) ~[SlimefunDynaTech.jar:?]
	at me.profelements.dynatech.dough.skins.PlayerHead.lambda$getItemStack$1(PlayerHead.java:53) ~[SlimefunDynaTech.jar:?]
	at me.profelements.dynatech.dough.skins.PlayerHead.getItemStack(PlayerHead.java:63) ~[SlimefunDynaTech.jar:?]
	at me.profelements.dynatech.dough.skins.PlayerHead.getItemStack(PlayerHead.java:51) ~[SlimefunDynaTech.jar:?]
	at me.profelements.dynatech.DynaTechItems.<clinit>(DynaTechItems.java:54) ~[SlimefunDynaTech.jar:?]
	... 14 more
[21:25:00] [Server thread/INFO]: [DynaTech] Disabling DynaTech vDEV - 201 (git 0feb2ee0)
```

## Environment (Required)
```
> sf versions
[22:00:17 INFO]: This Server uses the following setup of Slimefun:
Paper git-Paper-309 (MC: 1.20.2)
Slimefun 4.9-UNOFFICIAL
Metrics-Module #29
Java 17

Installed Addons: (11)
  SlimeHUD vDEV - 11 (git b6dc2d53)
  Gastronomicon vDEV - 8 (git 76336191)
  LiteXpansion vDEV - 192 (git 661862ed)
  FastMachines vBuild 11 (git d59490b)
  SoundMuffler v1.0-SNAPSHOT
  Bump vBuild 40 (git 811005e)
  ExtraHeads vDEV - 25 (git 8c29f73a)
  SfChunkInfo vDEV - 8 (git b1b94abb)
  DynaTech vDEV - 201 (git 0feb2ee0)
  ExtraGear vDEV - 13 (git c62047e2)
  SlimefunLuckyBlocks vDEV - 36 (git 60f0c8dc)
```

Since SF CI is down I pulled and built latest version myself, no modifications: 0589b21af395a87495be532c0f48893cf541c01a

**Comment by IAISI** [comment]
Duplicate of https://github.com/ProfElements/DynaTech/issues/195 my bad.
