### ISSUE TITLE
Dynatech 1.20.4 not work

### ISSUE THREAD

**Issue by Hiirooo** [ProfElements/DynaTech#219]
Error Generated: 2024-09-13-15-35

Java Environment:
  Operating System: Windows 10
  Java Version: 22.0.2

Server Software: Paper
  Build: git-Paper-485 (MC: 1.20.4)
  Minecraft v1.20.4-R0.1-SNAPSHOT

Slimefun Environment:
  Slimefun vRC - 37
  Caused by: DynaTech vMain - 41

Installed Addons (5)
  + InfinityExpansion DEV - 144 (git 9da37202)
  + AuraSkills 2.0.6
  + Supreme Dev - 1
  + Networks Dev - 3
  - DynaTech Main - 41

Installed Plugins (40):
  + LuckPerms 5.4.108
  + Vault 1.7.3-b131
  + FastAsyncWorldEdit 2.9.3-SNAPSHOT-748;1a31f39
  + WorldGuard 7.0.9+5934e49
  + Multiverse-Core 4.3.10
  + PlaceholderAPI 2.11.5
  + ProtocolLib 5.2.0-SNAPSHOT-679
  + GriefPrevention 16.18.1
  + Slimefun RC - 37
  + DecentHolograms 2.8.6
  + Skript 2.8.5
  + InfinityExpansion DEV - 144 (git 9da37202)
  + MythicMobs 5.6.1-${CI_COMMIT_SHORT_SHA}
  + Citizens 2.0.33-SNAPSHOT (build 3373)
  + Essentials 2.21.0-dev+24-0af4436
  + NexEngine 2.2.12
  + BlueSlimeCore 2.9.4.402
  + AuraSkills 2.0.6
  + TAB 4.1.2
  + Supreme Dev - 1
  + skript-yaml 1.5
  + skript-reflect 2.4
  + skript-placeholders 1.6.0
  + SkBee 3.5.0
  + PlayerAuctions 1.28.1
  + Networks Dev - 3
  + ModelEngine R4.0.5
  + LumberJack 5.3.0
  + InteractionVisualizer 1.18.8.0
  + ExcellentEnchants 3.6.5
  - DynaTech Main - 41
  + CrazyCrates 1.19.1
  + ConsoleSpamFix 1.10.0
  + CommandPanels 3.20.0.2
  + CombatLogX 11.4.0.1.1193
  + CMILib 1.4.5.2
  + ChatManager 3.7.7
  + BetonQuest 2.1.3
  + BestTools 2.2.1
  + AntiPopup 7.3

Block Info:
  World: spawn
  X: 734
  Y: 68
  Z: 889
  Material: BEEHIVE
  Block Data: org.bukkit.craftbukkit.v1_20_R3.block.impl.CraftBeehive
  State: org.bukkit.craftbukkit.v1_20_R3.block.CraftBeehive

Ticker-Info:
  Type: Synchronized

Slimefun Data:
  ID: DYNATECH_ALUMINUMMINERALIZED_APIARY
  Inventory: true
  Data: {"id":"DYNATECH_ALUMINUMMINERALIZED_APIARY"}

Stacktrace:

java.lang.IllegalStateException: zip file closed
	at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:846)
	at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:338)
	at java.base/java.util.jar.JarFile.getEntry(JarFile.java:516)
	at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:471)
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:209)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:169)
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at DynaTech.jar//me.profelements.dynatech.items.abstracts.AbstractTickingContainer$1.tick(AbstractTickingContainer.java:33)
	at Slimefun4-RC.jar//io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickBlock(TickerTask.java:184)
	at Slimefun4-RC.jar//io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.lambda$tickLocation$2(TickerTask.java:165)
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482)
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1646)
	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:447)
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1525)
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1226)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
	at java.base/java.lang.Thread.run(Thread.java:1570)

**Comment by Hiirooo** [comment]
![report dynatech](https://github.com/user-attachments/assets/a6fd4337-ea02-40d0-b70b-47a38ea18404)
after place block dynatech it gone

**Comment by ProfElements** [comment]
Please upgrade Slimefun to a dev version.
