### ISSUE TITLE
orechid error

### ISSUE THREAD

**Issue by aliakbartnt** [ProfElements/DynaTech#224]
## orechid after some time (my mean 3 s) remove 
[00:59:02 WARN]: [DynaTech]
[00:59:02 WARN]: [DynaTech] An Error occurred! It has been saved as:
[00:59:02 WARN]: [DynaTech] /plugins/Slimefun/error-reports/2024-09-21-00-59.err
[00:59:02 WARN]: [DynaTech] Please put this file on https://pastebin.com/ and report this to the developer(s).
[00:59:02 WARN]: [DynaTech] Bug Tracker: https://github.com/ProfElements/DynaTech/issues
[00:59:02 WARN]: [DynaTech]
[00:59:05 ERROR]: [Slimefun] X: 670 Y: 63 Z: -889 (DYNATECH_ORECHID)
[00:59:05 ERROR]: [Slimefun] has thrown 4 error messages in the last 4 Ticks, the Block has been terminated.
[00:59:05 ERROR]: [Slimefun] Check your /plugins/Slimefun/error-reports/ folder for details.
[00:59:05 ERROR]: [Slimefun]

## Steps to reproduce the Issue (Required)
![image](https://github.com/user-attachments/assets/6f91bff2-d52d-417c-9429-0668126b102e)
![image](https://github.com/user-attachments/assets/b5a32fea-e291-43a7-b67e-9b0bf8455c15)

## Expected behavior (Required)
after some times its remove

 - Minecraft Version:
 - CS-CoreLib Version: - 
 - Slimefun Version: Slimefun4 - DEV 1104 (git c9774)
 - Plugin Version: vmain 38
![image](https://github.com/user-attachments/assets/293644ff-40e3-4007-9dfc-8bb1b807ce25)
![image](https://github.com/user-attachments/assets/897a2d16-4b2c-4e35-ab8a-56720ac7ae77)

**Comment by aliakbartnt** [comment]
my software : purpur 1.20.6

**Comment by aliakbartnt** [comment]
java 21

**Comment by ProfElements** [comment]
Update to latest.

**Comment by aliakbartnt** [comment]
i do it but aggain not work
![image](https://github.com/user-attachments/assets/1fb25b86-2681-40ca-ad56-d8a8506d7622)
[11:08:19 WARN]: [DynaTech]
[11:08:19 WARN]: [DynaTech] An Error occurred! It has been saved as:
[11:08:19 WARN]: [DynaTech] /plugins/Slimefun/error-reports/2024-09-21-11-08.err
[11:08:19 WARN]: [DynaTech] Please put this file on https://pastebin.com/ and report this to the developer(s).
[11:08:19 WARN]: [DynaTech] Bug Tracker: https://github.com/ProfElements/DynaTech/issues
[11:08:19 WARN]: [DynaTech]
[11:08:22 ERROR]: [Slimefun] X: 670 Y: 63 Z: -889 (DYNATECH_ORECHID)
[11:08:22 ERROR]: [Slimefun] has thrown 4 error messages in the last 4 Ticks, the Block has been terminated.
[11:08:22 ERROR]: [Slimefun] Check your /plugins/Slimefun/error-reports/ folder for details.
[11:08:22 ERROR]: [Slimefun]

**Comment by ProfElements** [comment]
Please give me the error report that it specifies

**Comment by aliakbartnt** [comment]
Error Generated: 2024-09-21-11-12

Java Environment:
  Operating System: Windows Server 2019
  Java Version: 21.0.4

Server Software: Purpur
  Build: 1.20.6-2233-0d6766e (MC: 1.20.6)
  Minecraft v1.20.6-R0.1-SNAPSHOT

Slimefun Environment:
  Slimefun vDEV - 1104 (git c977454e)
  Caused by: DynaTech vMain - 46

Installed Addons (34)
  + SlimyTreeTaps DEV - 20 (git 963f0383)
  - LiteXpansion Dev - 193
  + ExoticGarden DEV - 78 (git 7f9a5f63)
  + InfinityExpansion DEV - 144 (git 9da37202)
  - DynaTech Main - 46
  + ShopGUIPlus 1.97.0
  + SlimefunWarfare DEV - 82 (git 0bb3ff87)
  + Networks DEV - 50 (git 3de3c9d6)
  + zMenu 1.0.3.3
  + SimpleMaterialGenerators DEV - 4 (git 5543cc8f)
  + SlimeTinker DEV - 84 (git 2c9f6155)
  + VillagerTrade DEV - 4 (git bcce2a41)
  + SoulJars DEV - 24 (git 78d1c6fa)
  + SlimefunOreChunks DEV - 15 (git 2520cb23)
  + SFAdvancements DEV - 25 (git 661a326b)
  + SimpleUtils DEV - 15 (git 4250fd5e)
  + SFMobDrops DEV - 6 (git d36aba47)
  + MobCapturer DEV - 33 (git 6fc26c35)
  + FoxyMachines DEV - 67 (git 0028aa93)
  + FNAmplifications DEV - 93 (git 7bc01100)
  - FluffyMachines Dev - 8
  + FlowerPower Dev - 2
  - EzChestShop 1.6.5
  + ExtraTools DEV - 36 (git 922c0324)
  + ExtraHeads DEV - 25 (git 8c29f73a)
  + ExtraGear DEV - 13 (git c62047e2)
  + ElectricSpawners DEV - 23 (git 6ec96773)
  + EcoPower DEV - 5 (git 5c1ecd68)
  + DyedBackpacks DEV - 17 (git 8b329e96)
  + DankTech2 DEV - 9 (git aa6c2209)
  + CrystamaeHistoria DEV - 81 (git 0c0efa95)
  + ColoredEnderChests DEV - 23 (git 4d041832)
  + BetterReactor DEV - 11 (git 88a98d28)
  + AuraSkills 2.2.1

Installed Plugins (103):
  + ViaVersion 5.0.2
  + LuckPerms 5.4.137
  + Vault 1.7.3-b131
  + ClearLag 3.2.2
  + PlaceholderAPI 2.11.6
  + WorldEdit 7.3.5+6880-8ba3d89
  + Slimefun DEV - 1104 (git c977454e)
  + SlimyTreeTaps DEV - 20 (git 963f0383)
  - LiteXpansion Dev - 193
  + LiteBans 2.15.1
  + ExoticGarden DEV - 78 (git 7f9a5f63)
  + InfinityExpansion DEV - 144 (git 9da37202)
  + ViaBackwards 5.0.1
  + ProtocolLib 5.3.0-SNAPSHOT-726
  + Essentials 2.21.0-dev+106-8b08a8f
  - DynaTech Main - 46
  + WorldGuard 7.0.10+d9424b1
  + ViaRewind 4.0.2
  + Multiverse-Core 4.3.1-b861
  + SuperVanish 6.2.20
  + nightcore 2.6.3
  + ShopGUIPlus 1.97.0
  + SlimefunWarfare DEV - 82 (git 0bb3ff87)
  + Networks DEV - 50 (git 3de3c9d6)
  + Citizens 2.0.35-SNAPSHOT (build 3489)
  + zMenu 1.0.3.3
  + DecentHolograms 2.8.9
  - HolographicDisplays 3.0.4
  + TAB 4.1.6
  + GriefPrevention 16.18.4
  + DiscordSRV 1.28.0
  + NexEngine 2.2.12
  + InvSeePlusPlus 0.28.0
  + EssentialsChat 2.21.0-dev+106-8b08a8f
  + ExcellentEnchants 4.1.0
  + RoseStacker 1.5.24
  + SimpleMaterialGenerators DEV - 4 (git 5543cc8f)
  + SlimeTinker DEV - 84 (git 2c9f6155)
  + AFKPlus 3.4.3
  + ServersNPC 4.7
  + zAuctionHouseV3 3.2.2.0
  + WorldGuardExtraFlags 4.2.4-SNAPSHOT
  + VillagerTrade DEV - 4 (git bcce2a41)
  + TradeSystem 2.6.0
  + TimeVote 1.5.1
  + Stratos 1.15.25
  + spark 1.10.34
  + SoulJars DEV - 24 (git 78d1c6fa)
  + SlimefunOreChunks DEV - 15 (git 2520cb23)
  + SFAdvancements DEV - 25 (git 661a326b)
  + SimpleUtils DEV - 15 (git 4250fd5e)
  + SFMobDrops DEV - 6 (git d36aba47)
  + Sellwand 1.7.1
  + PvPManager 3.18.26
  + PunishGUI 1.1.9
  + PlugManX 2.4.1
  + PlayerWarps 3.0.0-BETA17
  + PlayerKits2 1.12.3
  + packetevents 2.4.0
  + MyCommand 5.7.4
  - MoneyHunters 7.0.7 Basic
  + MobCapturer DEV - 33 (git 6fc26c35)
  + LockettePro 2.11.1
  + LightTitle 1.0.2
  + LaggRemover 2.0.6
  + ItemEdit 3.5.2
  + InvSeePlusPlus_Give 0.28.0
  + InvSeePlusPlus_Clear 0.28.0
  + InteractiveChat 4.2.11.0
  + InteractionVisualizer 1.18.11.0
  + HoloMobHealth 2.3.8.2
  + GSit 1.9.5
  + GrimAC 2.3.65
  + FoxyMachines DEV - 67 (git 0028aa93)
  + FNAmplifications DEV - 93 (git 7bc01100)
  - FluffyMachines Dev - 8
  + FlowerPower Dev - 2
  - EzChestShop 1.6.5
  + ExtraTools DEV - 36 (git 922c0324)
  + ExtraHeads DEV - 25 (git 8c29f73a)
  + ExtraGear DEV - 13 (git c62047e2)
  + EssentialsSpawn 2.21.0-dev+106-8b08a8f
  + EssentialsAFKRoom 1.0-SNAPSHOT
  + ElectricSpawners DEV - 23 (git 6ec96773)
  + EcoPower DEV - 5 (git 5c1ecd68)
  + DyedBackpacks DEV - 17 (git 8b329e96)
  + Drugs 6.3
  + DankTech2 DEV - 9 (git aa6c2209)
  + CustomF3Brand 1.2.1
  + CrystamaeHistoria DEV - 81 (git 0c0efa95)
  + CrateReloaded 2.3.13
  + ColoredEnderChests DEV - 23 (git 4d041832)
  + Chunky 1.4.10
  + ChatManager 1.21-6
  + ChatEmojis 2.4.1
  + BungeeGuard 1.3-SNAPSHOT
  + BetterRTP 3.6.13
  + BetterCommandSpy 2.0.4-b29
  + BetterReactor DEV - 11 (git 88a98d28)
  + BankPlus 6.2
  + AuraSkills 2.2.1
  + AFKPlusPrefix 1.3.5
  + Admin-GUI 1.9.0

Block Info:
  World: world
  X: 670
  Y: 63
  Z: -889
  Material: WITHER_ROSE
  Block Data: org.bukkit.craftbukkit.block.data.CraftBlockData
  State: org.bukkit.craftbukkit.block.CraftBlockState

Ticker-Info:
  Type: Asynchronous

Slimefun Data:
  ID: DYNATECH_ORECHID
  Inventory: false
  Data: {"energy-charge":"16384","id":"DYNATECH_ORECHID"}

Stacktrace:

java.lang.NullPointerException: Cannot invoke "me.profelements.dynatech.DynaTech.getTickInterval()" because the return value of "me.profelements.dynatech.DynaTech.getInstance()" is null
	at DynaTech.jar//me.profelements.dynatech.items.electric.machines.Orechid.tick(Orechid.java:59)
	at DynaTech.jar//me.profelements.dynatech.items.abstracts.AbstractTicker$1.tick(AbstractTicker.java:37)
	at Slimefun4 - DEV 1104 (git c9774).jar//io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickBlock(TickerTask.java:184)
	at Slimefun4 - DEV 1104 (git c9774).jar//io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickLocation(TickerTask.java:171)
	at Slimefun4 - DEV 1104 (git c9774).jar//io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickChunk(TickerTask.java:141)
	at Slimefun4 - DEV 1104 (git c9774).jar//io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.run(TickerTask.java:110)
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101)
	at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
