### ISSUE TITLE
Dynatech doesn't work

### ISSUE THREAD

**Issue by pump61** [ProfElements/DynaTech#225]
the plugin just doesn't start during server loading, sometimes it works and other times it doesn't

## Server Log / Error Report
[23:33:07] [Server thread/INFO]: [DynaTech] Enabling DynaTech vMain - 49
[23:33:07] [Server thread/ERROR]: Error occurred while enabling DynaTech vMain - 49 (Is it up to date?)
java.lang.NoSuchFieldError: Class org.bukkit.enchantments.Enchantment does not have member field 'org.bukkit.enchantments.Enchantment UNBREAKING'
	at me.profelements.dynatech.registries.Recipes.lambda$static$0(Recipes.java:34) ~[DynaTech.jar:?]
	at me.profelements.dynatech.dough.items.CustomItemStack.<init>(CustomItemStack.java:29) ~[DynaTech.jar:?]
	at me.profelements.dynatech.dough.items.CustomItemStack.<init>(CustomItemStack.java:34) ~[DynaTech.jar:?]
	at me.profelements.dynatech.registries.Recipes.<clinit>(Recipes.java:33) ~[DynaTech.jar:?]
	at me.profelements.dynatech.setup.DynaTechItemsSetup.setup(DynaTechItemsSetup.java:102) ~[DynaTech.jar:?]
	at me.profelements.dynatech.DynaTech.onEnable(DynaTech.java:72) ~[DynaTech.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:653) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:564) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:346) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1146) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[23:33:07] [Server thread/INFO]: [DynaTech] Disabling DynaTech vMain - 49

 - Minecraft Version: Current: git-Purpur-2176 (MC: 1.20.4)*
 - Slimefun Version: Dev - 1156
 - Plugin Version: Main - 49

**Comment by scorninpc** [comment]
This break 1.20.5 or lower, as this constants was added at 1.20.6

Maybe a check of version will be nice

**Comment by ProfElements** [comment]
I only support the latest minecraft version supported by slimefun. At time of writing i only support 1.20.6
