### ISSUE TITLE
Health must be between 0 and 43.0, but was 48.0 error

### ISSUE THREAD

**Issue by andris155** [ProfElements/DynaTech#55]
## Description (Required)

Health must be between 0 and 43.0, but was 48.0 error when use Healthy Item Band items.

## Steps to reproduce the Issue (Required)

1. Use Heath boost items.
2. Use vanilla max health attribute items.

/give @s minecraft:diamond_helmet{AttributeModifiers:[{AttributeName:"generic.max_health",Name:"generic.max_health",Amount:20,Operation:0,UUID:[I;1038774466,1042406287,1047209352,1673452821]}]} 1

## Expected behavior (Required)

Healthy Item Band items works perfectly without error.

## Server Log / Error Report

```
[18:56:53] [Server thread/WARN]: [DynaTech] Task #70158126 for DynaTech vDEV - 88 (git c06f0e25) generated an exception
java.lang.IllegalArgumentException: Health must be between 0 and 43.0, but was 48.0. (attribute base value: 20.0, player: IciAlex)
	at org.bukkit.craftbukkit.v1_16_R3.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:127) ~[patched_1.16.5.jar:git-Tuinity-"94f025a"]
	at me.profelements.dynatech.tasks.ItemBandTask.lambda$testItemBand$0(ItemBandTask.java:53) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Tuinity-"94f025a"]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Tuinity-"94f025a"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1475) ~[patched_1.16.5.jar:git-Tuinity-"94f025a"]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:419) ~[patched_1.16.5.jar:git-Tuinity-"94f025a"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1388) ~[patched_1.16.5.jar:git-Tuinity-"94f025a"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1120) ~[patched_1.16.5.jar:git-Tuinity-"94f025a"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) ~[patched_1.16.5.jar:git-Tuinity-"94f025a"]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

## Environment (Required)

Tuinity git-Tuinity-"c303521" (MC: 1.16.5)
Slimefun DEV - 864 (git 82366191)
Metrics-Module #21
Java 11

Installed Addons: (5)
  InfinityExpansion vDEV - 100 (git 65892de0)
  LiteXpansion vDEV - 138 (git 004e3c61)
  SlimefunFix v3.0
  FoxyMachines vDEV - 42 (git ae8d8aba)
  DynaTech vDEV - 90 (git 9f27da61)

**Comment by andris155** [comment]
https://www.youtube.com/watch?v=TsuA3aKVRlE

**Comment by ProfElements** [comment]
this is unsupported behavior. I do not expect people to be able to get attribute modifying items in any vanilla games.

**Comment by ProfElements** [comment]
i lied.

**Comment by ProfElements** [comment]
Fixed in a2855b6

**Comment by andris155** [comment]
Thanks

**Comment by ProfElements** [comment]
:+1:
